### ISSUE TITLE
disqus基础模式

### ISSUE THREAD

**Issue by JasonLin1230** [JasonLin1230/JasonLin1230.github.io#1]
* 故障：disqus基础模式暂时无法实现，cdn反代源站504

* 原因：disqus.com源站设置了保护，无法直接反代

* 解决方案：现在，我需要一个国外的服务器作为中间层进行跳转

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a public instance of [Staticman](https://staticman.net), which brings comments to static web sites.

Disqus has a plethora of shortcomings that deter many bloggers, say

1. privacy issues
2. slow load speed
3. no markdown support
4. poor SEO
5. high cost of migration

:information_source: You may see https://github.com/Pelican-Elegant/elegant/issues/288 for more links to posts about migrating from Disqus.

You may avoid these problems by switching to static comments powered by Staticman, which makes use of GitHub/GitLab Pull/Merge Requests. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

For working examples of Staticman, you may see

1. a popular Jekyll theme called [Beautiful Jekyll](https://github.com/daattali/beautiful-jekyll/), which has incorporated my port of [Minimal Mistake](https://github.com/mmistakes/minimal-mistakes/)'s Staticman integration.
1. [zcrc.me](https://zcrc.me/) [Source](https://gitlab.com/pcercuei/pcercuei.gitlab.io): a personal Jekyll blog with Markdown support and preview.
2. [my personal blog](https://lstu.fr/3s) [Source](https://gitlab.com/vincenttam/vincenttam.gitlab.io) powered by my tweaked Beautiful Hugo, with nested comments and comments preview.
3. a group of my [Staticman demo sites on Framagit](https://framagit.org/staticman-gitlab-pages).

:information_source: There're many ways leading to Rome, like JAM stack, Netlify Comments, etc.

**Comment by JasonLin1230** [comment]
Hi, thank you for your suggestion, I will seriously consider it.:grin:

**Comment by VincentTam** [comment]
> Hi, thank you for your suggestion, I will seriously consider it.

Nonetheless, the official Staticman instance isn't quite stable, as reported in https://github.com/eduardoboucas/staticman/pull/285 and https://github.com/eduardoboucas/staticman/issues/296.  To get Staticman in minutes, I suggest following the steps in [Beautiful Jekyll](https://github.com/daattali/beautiful-jekyll/), then read the outdated official docs to get an idea, and then pick your favourite theme from [my list of demo sites](https://framagit.org/staticman-gitlab-pages/).
