### ISSUE TITLE
[Error] Can't load web site

### ISSUE THREAD

**Issue by VincentTam** [JasonLin1230/JasonLin1230.github.io#2]
![Screenshot from 2019-06-25 22-55-26](https://user-images.githubusercontent.com/5748535/60132712-5ba8eb00-979c-11e9-930d-2aea3d9b7c04.png)

**Comment by JasonLin1230** [comment]
Hi, thank you for reporting this issue.
Actually, it works fine on my own machine.
Could you provide your OS version, browser version and other related information?

**Comment by VincentTam** [comment]
Thank you for response.

I think the problem is a cross-platform one.  Your site is not indexed by DuckDuckGo despite your sitemap.  You might try [reproducing this problem](https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fgodu.ink&t=h_&ia=web).

![Screenshot from 2019-06-26 10-05-27](https://user-images.githubusercontent.com/5748535/60162510-f8e63c80-97f9-11e9-9f51-95536c046c58.png)

**Comment by VincentTam** [comment]
This problem seems fixed, but it leads to a new issue #3.
