### ISSUE TITLE
Life is short, make it fast!

### ISSUE THREAD

**Issue by VincentTam** [JasonLin1230/JasonLin1230.github.io#3]
It takes more than ten seconds to loads.  That's quite long for normal blogs.  You might try using web optimized images.

![Screenshot from 2019-06-27 21-51-30](https://user-images.githubusercontent.com/5748535/60297079-bae73680-9927-11e9-934d-768b9169e048.png)

**Comment by JasonLin1230** [comment]
Hi, I have compressed most of the images and used cdn acceleration.
The reason my page loads slowly is mainly due to loading remote audios & video.

![s](https://user-images.githubusercontent.com/27892080/60775223-670ff500-a152-11e9-8902-2586d9570f9a.png)

**Comment by VincentTam** [comment]
Thanks for your work, but my browser ridicules me.  It gets loaded for an longer period of time.

![Screenshot from 2019-07-08 08-37-54](https://user-images.githubusercontent.com/5748535/60788012-ec4bd780-a15b-11e9-818b-8b3de0fe75ec.png)

I pressed reload, and it still takes nine seconds.  That will drive most netizens away from your site.

![Screenshot from 2019-07-08 08-42-50](https://user-images.githubusercontent.com/5748535/60788192-63816b80-a15c-11e9-828c-510629d93162.png)
